### ISSUE TITLE
feature request: option to only update draft releases

### ISSUE THREAD

**Issue by jeacott1** [xresloader/upload-to-github-release#19]
Hi,
 handy action, works well, but It would be very handy to be able to restrict updates to release types with this action so that there is no risk of modifying non draft releases for example.
perhaps options like :
update_drafts:true/false
update_prerelease:true/false
update_release:true/false

it would also be very useful if I could set draft as true/false in the initial instance but have the option to leave it as is if it exists (in the case where I want to upload to a non-draft release).
this action atm has the annoying property that if I set "draft=true" it will revert any release it finds to draft state. (same for pre-release).

**Comment by owt5008137** [comment]
Good idea. I will add these options later. Maybe we also need a option to just update a old release and skip to create any new release if not existed.

**Comment by owent** [comment]
`draft` and `prerelease` status will not changed when these options are unset now.
And I think we can set `overwrite` to `false` when updating a aleady existed release. Or use [if](https://docs.github.com/cn/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idif) to control the whole job.
