### ISSUE TITLE
Feature Request: Create release on other repo

### ISSUE THREAD

**Issue by AriaMoradi** [xresloader/upload-to-github-release#21]
consider the use case where this action is going to run on a repo named "Application", I want to create the release on the repo named "Application-nightly".

I would imagine setting a key like `target_repo: "githubUser/Application-nightly"`

**Comment by owent** [comment]
Thanks for your suggestion. I will add it some times later.

**Comment by owent** [comment]
Implemented in [v1.3.6](https://github.com/xresloader/upload-to-github-release/releases/tag/v1.3.6)
