### ISSUE TITLE
Unable to upload asset to existing release

### ISSUE THREAD

**Issue by RadxaYuntian** [xresloader/upload-to-github-release#34]
Our use case involves building multiple system images for our product. As such to avoid running out disk spaces during release action we [create an empty release](https://github.com/radxa-build/rock-3b/blob/91d201771ea6e42f6d9478adc8d1bf22433e3020/.github/workflows/build.yml#L18) first, then [upload images](https://github.com/radxa/debos-build-action/blob/9f52cdae25928a80d431da7d5570a15cc627ec3b/action.yml#L25) from each matrix runner. This worked fine [last month](https://github.com/radxa-build/rock-3b/actions/runs/2251687014) but when the task was scheduled to run this month the same code [now failed](https://github.com/radxa-build/rock-3b/runs/6680921756?check_suite_focus=true#step%3A4%3A10134=).

The error message says `Error: Try to update release 20220601-0037 for radxa-build/rock-3b failed: Validation Failed: {"resource":"Release","code":"already_exists","field":"tag_name"}` which doesn't seems like an error but an intended result when we want to upload additional assets to an existing release.

**Comment by owent** [comment]
Thanks and could you please try the `main` branch? I will release a new version if it works.

**Comment by owent** [comment]
Thanks and published.
