### ISSUE TITLE
Need way to not touching draft/prerelease status

### ISSUE THREAD

**Issue by RadxaYuntian** [xresloader/upload-to-github-release#39]
We are using GitHub to build system images for our products, so we created custom actions to build images, and use this action to upload the artifacts. The per-product workflow first runs a job to create an empty release, then uses matrix to build multiple images in parallel, each uploading their artifacts individually.

This scheme worked well, but now we are trying to mark our (automatic) release as prerelease first, and then test them to promote as official release. This is when we discovered that the prerelease status is overwritten by this action. This becomes problematic when we also have some workflows that want to create normal release, so we will have to update every workflows and custom actions to pass their prerelease and draft status.

What we want is for the action to upload-to-github-release and nothing more. I believe this is what [actions/upload-release-asset](https://github.com/actions/upload-release-asset) was doing but that one was archived. Their suggested alternative does not support uploading to existing releases AFAICT so we settled with this action.

**Comment by owent** [comment]
Thanks for the suggestion, I will fix this problem several days later.

**Comment by owent** [comment]
`v1.3.8` is released and title, draft and prerelease status will not be changed now if `draft` and `prerelease` options are unset.
