### ISSUE TITLE
Try to create release failed: Bad credentials

### ISSUE THREAD

**Issue by liudonghua123** [xresloader/upload-to-github-release#4]
I have a workflow https://github.com/liudonghua123/test/actions/runs/58612734/workflow. And in the last step, I got `Try to create release end for liudonghua123/test failed: Bad credentials` error. It's really strange. I can't find any help info about this.

The full stop logs is
```
 Run xresloader/upload-to-github-release@v14s
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
  with:
    file: out/depot_tools.tar.xz;out/dart-sdk.tar.xz.part*
    tags: true
    draft: false
    overwrite: false
    prerelease: false
    verbose: false
    update_latest_release: false
  env:
    GITHUB_TOKEN: ***
Found tag push: ${match_tag[1]}.
File found to upload: out/depot_tools.tar.xz
File found to upload: out/dart-sdk.tar.xz.partaa
File found to upload: out/dart-sdk.tar.xz.partab
File found to upload: out/dart-sdk.tar.xz.partac
File found to upload: out/dart-sdk.tar.xz.partad
Try to get release end from liudonghua123/test : Bad credentials
Try to get git tags/end for liudonghua123/test
Get git tags/end for liudonghua123/test: Bad credentials
Try to create release end for liudonghua123/test
Try to create release end for liudonghua123/test failed: Bad credentials
HttpError: Bad credentials
    at /home/runner/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:14845:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
##[error]Try to create release end for liudonghua123/test failed: Bad credentials
HttpError: Bad credentials
    at /home/runner/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:14845:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**Comment by owt5008137** [comment]
@liudonghua123 
Your action takes almost 2 hours. According to https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#about-the-github_token-secret , the generated ```GITHUB_TOKEN``` will expires after 60 minutes. If you want to upload your assets after a long time job, you can try to create a personal token, add it into secrets of your repository and the set it to

```yaml
env:
      GITHUB_TOKEN: ${{ secrets.YOUR_SECRET_NAME_OF_PERSONAL_TOKEN }}
````

See these documents for detail:
https://help.github.com/en/actions/configuring-and-managing-workflows/authenticating-with-the-github_token#permissions-for-the-github_token
https://help.github.com/en/github/authenticating-to-github/creating-a-personal-access-token-for-the-command-line
https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets

Hope helpful.

**Comment by liudonghua123** [comment]
@owt5008137 Thanks for detailed explanation, now I see it.
