### ISSUE TITLE
1.3.8 is not working as intended for draft/prerelease

### ISSUE THREAD

**Issue by RadxaYuntian** [xresloader/upload-to-github-release#41]
Create empty non draft prerelease first.
https://github.com/RadxaYuntian/upload-to-github-release/commit/5726e7219f5ac39acf13c0e7cbcdd3109c0be067: prerelease become draft
https://github.com/RadxaYuntian/upload-to-github-release/commit/52c25db546343c9cd600ba50b5e9dc505ab5a2db: prerelease become release

**Comment by owent** [comment]
You should put `xresloader/upload-to-github-release` just after `softprops/action-gh-release`. Or `xresloader/upload-to-github-release` may run before `softprops/action-gh-release`. `xresloader/upload-to-github-release` will not change these options only when update a existed release, or it will create a new release with default options(which means `draft` and `prerelease` are both `false`).

**Comment by RadxaYuntian** [comment]
> You should put xresloader/upload-to-github-release just after softprops/action-gh-release but in the same job. Or xresloader/upload-to-github-release may run before softprops/action-gh-release. 

I have set up [needs](https://github.com/RadxaYuntian/upload-to-github-release/commit/5726e7219f5ac39acf13c0e7cbcdd3109c0be067#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R30) so `upload-to-github-release` always run after `action-gh-release` is done.

**Comment by RadxaYuntian** [comment]
I have created a [new workflow](https://github.com/RadxaYuntian/upload-to-github-release/actions/runs/3436262971/workflow) according to what you said, and this one changed prerelease to draft as well:
![image](https://user-images.githubusercontent.com/95260730/201076186-192a9070-b2a7-4bb4-ade5-9a22e5bdb721.png)

**Comment by owent** [comment]
Thanks and it's fixed in v1.3.9 now.
I have create a test at https://github.com/xresloader/upload-to-github-release-test/blob/main/.github/workflows/release.yml

**Comment by RadxaYuntian** [comment]
Confirmed working on my 2 test cases.
