### ISSUE TITLE
File upload not found

### ISSUE THREAD

**Issue by TheMaverickProgrammer** [xresloader/upload-to-github-release#45]
The issue #44 was preemptively closed without much testing. The newest version changes the drive slash only I think? And it still fails:

![image](https://user-images.githubusercontent.com/91709/218238097-869bd461-e575-44e2-98e2-6f2a6fe0fd91.png)

**Comment by owent** [comment]
The slash  problem  is  tested in https://github.com/xresloader/upload-to-github-release-test/actions/runs/4150466015.
I will check if there is  any other problem.
Thanks.

**Comment by TheMaverickProgrammer** [comment]
https://github.com/xresloader/upload-to-github-release-test/actions/runs/4150466015/workflow

The test image is on ubuntu. Try it on windows too.

**Comment by owent** [comment]
@TheMaverickProgrammer 
This problem should be fixed now, we have test it in https://github.com/xresloader/upload-to-github-release-test/actions/runs/4155119464 and the release is here (https://github.com/xresloader/upload-to-github-release-test/releases/tag/main-79ccc08b).

Could you please test v1 branch if you have time? I will raise another PR later if v1 branch can solve your case.

**Comment by TheMaverickProgrammer** [comment]
I'll try your branch today.

**Comment by TheMaverickProgrammer** [comment]
@owent How am I supposed to test? I've tried `@v1` the commit hash directly (which github says doesn't support) and the release tag name:

![image](https://user-images.githubusercontent.com/91709/218324662-4ad3284f-aee0-4aff-8298-0fb8b8c530ca.png)

![image](https://user-images.githubusercontent.com/91709/218324715-a7e0bc4b-a2b7-4333-b201-a4227aebb4b8.png)

**Comment by owent** [comment]
> @owent How am I supposed to test? I've tried `@v1`, the commit hash directly (which github says doesn't support), and the release tag name:
> 
> ![image](https://user-images.githubusercontent.com/91709/218324662-4ad3284f-aee0-4aff-8298-0fb8b8c530ca.png)
> 
> ![image](https://user-images.githubusercontent.com/91709/218324715-a7e0bc4b-a2b7-4333-b201-a4227aebb4b8.png)
> 

Just use 、xresloader/upload-to-github-release@v1、.

**Comment by TheMaverickProgrammer** [comment]
Ok I'll try that.

**Comment by TheMaverickProgrammer** [comment]
![image](https://user-images.githubusercontent.com/91709/219890208-36618a41-6ac0-4e31-bb9e-4bc7552e17f6.png)
It works! Thank you so much!

**Comment by TheMaverickProgrammer** [comment]
![image](https://user-images.githubusercontent.com/91709/219892089-5d558e06-901a-4dbf-b21e-f8c859cd88a1.png)
Proof

**Comment by owent** [comment]
Thanks and it's published in [v1.3.11](https://github.com/xresloader/upload-to-github-release/releases/tag/v1.3.11) .
