### ISSUE TITLE
BUG: target_repo and target_owner are set to the same

### ISSUE THREAD

**Issue by twiddli** [xresloader/upload-to-github-release#46]
target_repo is set to target_owner

https://github.com/xresloader/upload-to-github-release/blob/v1/src/index.ts#L77

Additional:
Would be nice if the release_name was configurable

**Comment by owent** [comment]
Thanks, this problem is fixed and published by [v1.3.12](https://github.com/xresloader/upload-to-github-release/releases/tag/v1.3.12).
And also I add a option (`default_release_name`) to set the release name when creating new release.
