### ISSUE TITLE
[FEATURE REQUEST] Add ability to put commits into description of release between current and previous release

### ISSUE THREAD

**Issue by Parmjot-Singh** [xresloader/upload-to-github-release#48]
I would assume this would only work with tagged releases.
I want to be able to see the commits in between releases, maybe formatted like below

---

> # (Release title)
> 
> ### Changes
> `32fd834` (commit title)
> `d632gd3` (commit title)
> `f237qh4` (commit title)
> `12zv4ds` (commit title)

Obviously replacing the commit (tags? codes? I'm unsure what they're called) with the actual ones.

---

I don't see any way of doing this automatically, and I don't want to do this manually. This feature would be a really nice to have.

**Comment by owent** [comment]
I think it's not the purpose of this plugin, while I can add a option to set release description when create it.
Or you can use the existed release by `release_id` option.
