### ISSUE TITLE
Files are loaded into memory instead of streamed

### ISSUE THREAD

**Issue by enumag** [xresloader/upload-to-github-release#52]
Hi, I checked your source code and found this line:

https://github.com/xresloader/upload-to-github-release/blob/8e0ffc2bf70a36035a8b5479d0903041cb11423f/src/index.ts#L721C37-L721C49

Releases can contain several large files so this way the runner can easily run out of memory and crash.

I found this while looking for alternatives when I discovered the [same issue in another similar tool](https://github.com/softprops/action-gh-release/issues/353#issuecomment-1793854640).

**Comment by owent** [comment]
Good point and thanks.

**Comment by enumag** [comment]
I'm no JS expert but probably you need to use something like this: https://www.geeksforgeeks.org/node-js-fs-createreadstream-method/

**Comment by owent** [comment]
> I'm no JS expert but probably you need to use something like this: https://www.geeksforgeeks.org/node-js-fs-createreadstream-method/

GitHub's APIs do not accept read stream as data parameter. I will try to use `@file_path` to see if it will use stream internally.

**Comment by enumag** [comment]
Ouch... that would be rather nasty if Octokit itself requires the data to be loaded in memory. 😳 I hope it's not the case.

**Comment by owent** [comment]
I have raise #55 to try to use `@file_path` to upload file. But I have no repo which can be used to test a large asset file.
Could you please try `v1` branch or `main` branch to see if it work?

**Comment by enumag** [comment]
It doesn't work. The action succeeded and seemingly did actually upload the files however the files are just a few bytes large and contain the path to the file in the worker rather than the correct content.

**Comment by owent** [comment]
Thanks, I will try to find another way to fix this problem later.
