### ISSUE TITLE
GITHUB_TOKEN environment variable is unnecessary

### ISSUE THREAD

**Issue by enumag** [xresloader/upload-to-github-release#54]
Some other similar tools don't require a token to be explicitly passed. They have the option to do it but it isn't required. The `github.token` context value is used as default.

See https://docs.github.com/en/actions/learn-github-actions/contexts#github-context

**Comment by owent** [comment]
Could you please provide a  example of plugin which do not require a token to be explicitly passed? I didn't find the javascript API to read `github.token` from context object.

**Comment by enumag** [comment]
Sure, this one doesn't require it and is written in JS (well TS).

https://github.com/softprops/action-gh-release

On 07-Nov-23 10:16:35, WenTao Ou ***@***.***> wrote:
Could you please provide a example of plugin which do not require a token to be explicitly passed? I didn't find the javascript API to read github.token from context object.
