### ISSUE TITLE
Update action.yml to support node20

### ISSUE THREAD

**Issue by bogenlos** [xresloader/upload-to-github-release#60]
Please upgrade node version in action.yml due to [this](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

```
runs:
  using: "node20"
```
 
I'm getting this warning on execution:

Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: xresloader/upload-to-github-release@v1.4.2. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.

**Comment by owent** [comment]
Thanks and v1.5.0 use node20 now.
