### ISSUE TITLE
default_release_body/_path

### ISSUE THREAD

**Issue by Mikk155** [xresloader/upload-to-github-release#63]
default_release_body doesn't seems to update the body when the target is an existing release.

default_release_body_path doesn't seems to propertly work unless i am missing something:
```yaml
default_release_body_path: CHANGELOG.md
```
Wich ``CHANGELOG.md`` is on the root folder

**Comment by owent** [comment]
This option is used to create release, not update it. We usually only want to update assets without change anything of a existed release.

**Comment by Mikk155** [comment]
sounds fine for my needs, if another variable can be added as well i'd suggest ``update_release_body_append`` boolean
- true
   - appends the ``update_release_body_path`` to the body
- false
  - re write the whole body with ``update_release_body_path``

**Comment by owent** [comment]
`update_release_body`, `update_release_body_path` and `update_release_body_append` are available in v1.6.0 now.
