### ISSUE TITLE
Upload failed when file size is greater than 2GiB

### ISSUE THREAD

**Issue by shenxianpeng** [xresloader/upload-to-github-release#68]
`xresloader/upload-to-github-release` seems not to support uploading a file when its size is greater than 2GiB. 

Here is the failed output:

```
[draft-release](https://github.com/cpp-linter/clang-tools-static-binaries/actions/runs/10996141054/job/30545787497#step:4:723)

Upload asset: clang-tidy-19_macosx-amd64 failed => File size (2183057448) is greater than 2 GiB
RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2183057448) is greater than 2 GiB
    at tryCreateBuffer (node:fs:410:13)
    at Object.readFileSync (node:fs:463:14)
    at run (file:///home/runner/work/_actions/xresloader/upload-to-github-release/v1/lib/index.js:39789:52)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Here is the failed run: https://github.com/cpp-linter/clang-tools-static-binaries/actions/runs/10996141054

**Comment by owent** [comment]
According to <https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas> every file in release must be under 2GB.
