### ISSUE TITLE
Fail to upload `.app` file with `/` path

### ISSUE THREAD

**Issue by BTMuli** [xresloader/upload-to-github-release#69]
https://github.com/BTMuli/ShufflePlay/actions/runs/11717702041/job/32637837398

**Comment by owent** [comment]
The problem is there are many files have the same names.(Info.plist for example). The asset file names can not be same in one release, Please try to package these files into a zip file and upload this zip file.

**Comment by BTMuli** [comment]
Sorry, it's my problem, I mistakenly thought that `.app` file was a single file, but in fact macOS apps are all in the form of folders and recognize app of `.app`  specially.😑
